version: '3.2'

services:
    portainer:
        image: portainer/portainer
        container_name: ws-portainer
        restart: always
        ports:
            - 9095:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    siemdemo-mysql:
        image: mysql:8.0.19
        # volumes:
        #     - ~/volumes/jhipster/siemdemo/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=siemdemo
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
 

networks:
    elk:
        driver: bridge

volumes:
    elasticsearch:
